---
title: "Risk Analyzer"
output:
    flexdashboard::flex_dashboard:
        orientation: columns
        theme: 
          bootswatch: "lux"
          bg: "white"
          fg: "white"
          primary: "#18bc9c"
          secondary: "#18bc9c"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo    = FALSE,
    message = FALSE,
    warning = FALSE
)

# SHINY
library(shiny)
library(shinyjs)
library(plotly)
library(flexdashboard)

# ANALYSIS
library(tidyverse)
library(lubridate)
library(tidyquant)
library(timetk)
library(extraDistr)
library(furrr)
library(correlationfunnel)
library(gt)


source("functions/adspend_profile.R")

info_card <- function(
    title, value, sub_value,
    main_icon = "chart-line", 
    sub_icon = "arrow-up",
    border_color = "#18bc9c", 
    text_color = "#18bc9c", 
    sub_text_color = "#18bc9c"
) {
    
    div(
        class = "panel panel-default",
        style = str_glue("padding: 20px; border-color: {border_color}; border-style: solid;"),
        div(
            class = str_glue("panel-body"),
            p(class = "pull-right", icon(class = "fa-4x", main_icon), style = str_glue("color:{text_color}")),
            h4(title),
            h5(value),
            p(
                style = str_glue("color:{sub_text_color}"),
                icon(sub_icon),
                tags$small(sub_value)
            )
        )
    )
    
}
```

``` {css}
.chart-title {
  background-color: black;
  color: white;
}

.chart-stage {
  background-color: black;
}

.section.sidebar {
  background-color: black;
}

.navbar.navbar-inverse {
  background-color: #18bc9c!important;
  box-shadow: 3px 3px 5px black;
}

.navbar-dark .navbar-brand, .navbar.navbar-inverse .navbar-brand {
  color:black;
}

.navbar.navbar-inverse ul.nav.navbar-nav>li.active>a {
  color:black;
}

.dashboard-column {
  background-color: black;
}

.section {
  background-color: black;
}

body {
  background-color:black;
}

.selectize-dropdown {
  background-color:black;
}
.selectize-input.full {
  background-color:black;
}
.selectize-input, .selectize-control.single .selectize-input.input-active {
  background-color:black;
}
.selectize-dropdown .active {
  background-color: #18bc9c;
  color: #f2f2f2;
}

.form-control {
    background-color:black;
}
.form-control:active{
    background-color:black;
}
.form-control:hover{
    background-color:black;
}
.form-control:focus{
    background-color:black;
}

.datepicker {
    background-color:black;
}
.datepicker .datepicker-switch:hover, .datepicker .prev:hover, .datepicker .next:hover, .datepicker tfoot tr th:hover {
    background-color:#18bc9c;
}
.datepicker table tr td.day:hover {
    background-color:#18bc9c;
}
.datepicker table tr td.month:hover {
    background-color:#18bc9c;
}
.datepicker table tr td.year:hover {
    background-color:#18bc9c;
}

.nav-tabs .nav-link.active, .nav-tabs>li>a.active {
    background-color:#18bc9c;
}

```



# Facebook Adspend Project

## Column {.sidebar}

<br>


#### What does the app do?

> Calculates the investment risk in a project decision. 

<hr>

#### Investment Controls

```{r}

useShinyjs(rmd = TRUE)

shiny::dateInput(
  inputId = "start_date",
  label = "Start Date",
  value = "2021-10-01"
)

shiny::numericInput(
    inputId = "average_roas",
    label = "Average ROAS",
    value = 3.5,
    step = 0.5
)

shiny::sliderInput(
    inputId = "n_months_total",
    label = "Investment Horizon (Months)",
    value = 24,
    min = 12, 
    max = 12*4,
    step = 12, 
)

shiny::sliderInput(
    inputId = "n_months_learn",
    label = "Learn Horizon (Months)",
    value = 5,
    min = 3, 
    max = 6,
    step = 1, 
)

shiny::sliderInput(
    inputId = "n_months_scale",
    label = "Scale Horizon (Months)",
    value = 5,
    min = 1, 
    max = 3,
    step = 1, 
)

shiny::numericInput(
    inputId = "adspend_learn",
    label = "Adspend Learn",
    value = 3000,
    step = 1000, 
    min = 0
)

shiny::numericInput(
    inputId = "adspend_scale",
    label = "Adspend Scale",
    value = 30000,
    step = 10000, 
    min = 0
)

fluidRow(
    column(2,
        actionButton(inputId = "apply", label = "Apply", icon = icon("play"))
    ),
    column(2, style = "margin-left: 80px;", 
        actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))
    )
)

observeEvent(eventExpr = input$reset, handlerExpr = {
  
    updateDateInput(
        inputId = "start_date",
        value = "2021-10-01"
    )
    
    updateNumericInput(
        inputId = "average_roas",
        value = 3.5
    )
  
    updateSliderInput(
        inputId = "n_months_total",
        value = 24
    )
  
    updateSliderInput(
        inputId = "n_months_learn",
        label = "Learn Horizon (Months)",
        value = 5,
        min = 3, 
        max = 6,
        step = 1
    )

    updateSliderInput(
        inputId = "n_months_scale",
        label = "Scale Horizon (Months)",
        value = 5,
        min = 1, 
        max = 3,
        step = 1, 
    )

    updateNumericInput(
        inputId = "adspend_learn",
        label = "Adspend Learn",
        value = 3000,
        step = 1000, 
        min = 0
    )

    updateNumericInput(
        inputId = "adspend_scale",
        label = "Adspend Scale",
        value = 30000,
        step = 10000, 
        min = 0
    )

    shinyjs::delay(ms = 300, expr = {
        shinyjs::click(id = "apply")
    })
 
  
})


```

<hr>


```{r}
# LOGIC

rv <- reactiveValues()

observeEvent(input$apply, {
    
    req(input$start_date)
    req(input$average_roas)
    req(input$n_months_total)
    req(input$n_months_learn)
    req(input$n_months_scale)
    req(input$adspend_learn)
    req(input$adspend_scale)
    
    rv$input_start_date <- as_date(input$start_date)
    rv$input_average_roas <- input$average_roas
    rv$input_n_months_total <- input$n_months_total
    rv$input_n_months_learn <- input$n_months_learn
    rv$input_n_months_scale <- input$n_months_scale
    rv$input_adspend_learn <- input$adspend_learn
    rv$input_adspend_scale <- input$adspend_scale
    
    
    rv$adspend_profile_tbl <- create_adspend_profile(
        start_date       = as_date(input$start_date),
        average_roas     = as.numeric(input$average_roas),
        n_months_total   = as.numeric(input$n_months_total),
        n_months_learn   = as.numeric(input$n_months_learn),
        n_months_scale   = as.numeric(input$n_months_scale),
        adspend_learn    = as.numeric(input$adspend_learn),
        adspend_scale    = as.numeric(input$adspend_scale)
    )
    
    rv$project_summary_tbl <- rv$adspend_profile_tbl %>% 
        summarize_adspend_project()
    
}, ignoreNULL = FALSE)
```






## Column 

<br>

### Project Investment Profile

```{r}
fluidPage(
    div(style = "height: 150vh; overflow-y: scroll;",
        tabsetPanel(
            tabPanel(
                title = "Results",
                uiOutput("results")
            ),
            tabPanel(
                title = "Investment Profile",
                uiOutput("gt_table")
            )
        )
    )
)

output$results <- renderUI({
    
    req(rv$adspend_profile_tbl)
    req(rv$project_summary_tbl)
    
    pr <- rv$project_summary_tbl$estimated_profit
    npv <- rv$project_summary_tbl$npv
    pm <- rv$project_summary_tbl$profit_margin
    revenue <- rv$project_summary_tbl$estimated_revenue
    # npv <- -500
    
    g1 <- rv$adspend_profile_tbl %>% 
        plot_revenue_profit(.interactive = FALSE) +
        theme(
            panel.background = element_rect(fill = "black"),
            plot.background = element_rect(fill = "black"),
            text = element_text(colour = "white"),
            legend.background = element_rect(fill="black")
        ) +
        scale_color_manual(values = c("#18bc9c", "#fec403"))
    
    g2 <- rv$adspend_profile_tbl %>% 
        plot_cum_profit(.interactive = FALSE) +
        theme(
            panel.background = element_rect(fill = "black"),
            plot.background = element_rect(fill = "black"),
            text = element_text(colour = "white"),
            legend.background = element_rect(fill="black")
        ) +
        scale_color_manual(values = c("#18bc9c", "#fec403"))
    
    g3 <- rv$adspend_profile_tbl %>% 
        plot_profit_breakdown(.interactive = FALSE) +
        theme(
            panel.background = element_rect(fill = "black"),
            plot.background = element_rect(fill = "black"),
            text = element_text(colour = "white"),
            legend.background = element_rect(fill="black")
        )
        
    
    tagList(
        shiny::fluidRow(
            column(
                4,
                info_card(
                    title = "NPV (EST PROFIT)", 
                    value = str_glue("{scales::dollar(npv)} ({scales::dollar(pr)})"), 
                    text_color = ifelse(npv > 0, "#18bc9c", "red"),
                    sub_value = ifelse(npv > 0, "positive", "negative"),
                    sub_icon = NULL, 
                    sub_text_color = ifelse(npv > 0, "#18bc9c", "red"),
                    border_color = ifelse(npv > 0, "#18bc9c", "red")
                )
            ),
            column(
                4,
                info_card(
                    title = "Revenue (Est)", 
                    value = scales::dollar(revenue), 
                    text_color = ifelse(revenue > 1e6, "#18bc9c", "red"),
                    sub_value = ifelse(revenue > 1e6, ">$1M", "<$1M"),
                    sub_icon = NULL, 
                    sub_text_color = ifelse(revenue > 1e6, "#18bc9c", "red"),
                    border_color = ifelse(revenue > 1e6, "#18bc9c", "red")
                )
            ),
            column(
                4,
                info_card(
                    title = "Profit Margin (Est)", 
                    value = round(pm, 2), 
                    text_color = ifelse(pm > 0.20, "#18bc9c", "red"),
                    sub_value = ifelse(pm > 0.20, "> 0.20", "< 0.20"),
                    sub_icon = NULL, 
                    sub_text_color = ifelse(pm > 0.20, "#18bc9c", "red"),
                    border_color = ifelse(pm > 0.20, "#18bc9c", "red")
                )
            )
            
        ),
        br(),
        
        fluidRow(
            column(
                width = 4,
                ggplotly(g1)
            ),
            column(
                width = 4,
                ggplotly(g2)
            ),
            column(
                width = 4,
                ggplotly(g3)
            )
        )
        
    )
    
    
    
})

output$gt_table <- render_gt({
    
    req(rv$adspend_profile_tbl)
    req(rv$input_n_months_learn)
    req(rv$input_n_months_scale)
    req(rv$input_n_months_total)
    
    
    N_MONTHS_LEARN <- rv$input_n_months_learn
    N_MONTHS_SCALE <- rv$input_n_months_scale
    N_MONTHS_TOTAL <- rv$input_n_months_total

    adspend_wide_tbl <- rv$adspend_profile_tbl %>%
        pivot_longer(cols = -c(date)) %>%
        pivot_wider(id_cols = name, names_from = c(date), values_from = value) %>%
        mutate(name = str_replace_all(name, "_", " ") %>% str_to_title()) %>%
        mutate(name = ifelse(name == "Roas", "ROAS", name)) %>%
        mutate(name = str_replace(name, "Fb", "FB")) %>%
        mutate(group = case_when(
            str_detect(name, "Period") ~ "0-Info",
            str_detect(name, "^Cost") ~ "2-Costs",
            str_detect(name, "^Profit") ~ "3-Profit",
            TRUE ~ "1-Revenue"

        )) %>%
        select(group, everything())

    adspend_wide_tbl %>%
        group_by(group) %>%
        gt(rowname_col = "name") %>%
        tab_spanner(
            label = "Learn",
            id = "learn",
            columns = 2:(N_MONTHS_LEARN+2)
        ) %>%
        tab_spanner(
            label = "Scale",
            id = "scale",
            columns = (N_MONTHS_LEARN+3):(N_MONTHS_LEARN+N_MONTHS_SCALE+2)
        ) %>%
        tab_spanner(
            label = "Automate",
            id = "automate",
            columns = (N_MONTHS_LEARN+N_MONTHS_SCALE+3):(N_MONTHS_TOTAL+2)
        ) %>%
        fmt_currency(
            columns = everything(),
            rows    = c(3, 4:11),
            decimals = 0,
            accounting = TRUE
        ) %>%
        tab_style(
            style = cell_fill(color = "red", alpha = 0.9),
            locations = cells_column_spanners("learn")
        ) %>%
        tab_style(
            style = cell_fill(color = "yellow", alpha = 0.9),
            locations = cells_column_spanners("scale")
        ) %>%
        tab_style(
            style = cell_fill(color = "green", alpha = 0.9),
            locations = cells_column_spanners("automate")
        ) %>%
        tab_style(
            style = cell_text(weight = "bold"),
            locations = cells_row_groups()
        ) %>%
        tab_options(
            table.background.color = "#FFFFFF00",
            column_labels.font.size = px(10),
            column_labels.font.weight = "bold",
            table.font.color = "white",
            table.font.size = px(12L)
        )

}, height = "700px")


```




# Monte Carlo Simulation

## Column {.sidebar}

<br>



#### Simulation Controls


```{r}

shiny::sliderInput(
    inputId = "n_simulations",
    label = "Simulations",
    min = 10, 
    max = 200, 
    value = 20,
    step = 10
)

shiny::sliderInput(
    inputId = "roas_dist",
    label = "ROAS (min/max)", 
    value = c(1, 5),
    min = -10,
    max = 10,
    step = 0.5
)

shiny::sliderInput(
    inputId = "n_months_learn_dist",
    label = "Learn Months (min/max)", 
    value = c(3, 6),
    min = 2,
    max = 8
)

shiny::sliderInput(
    inputId = "n_months_scale_dist",
    label = "Scale Months (min/max)", 
    value = c(1, 3),
    min = 1,
    max = 4
)

actionButton(inputId = "run", label = "Run", icon = icon("play"))


```

```{r}
rv2 <- reactiveValues()

observeEvent(input$run, {
    
    req(input$n_simulations)
    req(input$roas_dist)
    req(input$n_months_learn_dist)
    req(input$n_months_scale_dist)
    
    rv2$input_n_simulations <- input$n_simulations
    rv2$input_roas_dist <- input$roas_dist
    rv2$input_n_months_learn_dist <- input$n_months_learn_dist
    rv2$input_n_months_scale_dist <- input$n_months_scale_dist
    
    N_SIMULATIONS <- rv2$input_n_simulations
    
    set.seed(123)
    rv2$simulation_grid_tbl <- tibble(
        average_roas    = rtriang(
            n = N_SIMULATIONS, 
            a = input$roas_dist[1], 
            b = input$roas_dist[2], 
            c = mean(c(input$roas_dist[1], 
                       input$roas_dist[2]))
        ),
        n_months_learn  = rtriang(
            n = N_SIMULATIONS, 
            a = input$n_months_learn_dist[1], 
            b = input$n_months_learn_dist[2], 
            c = mean(c(input$n_months_learn_dist[1],
                       input$n_months_learn_dist[2]))
        ) %>% round(),
        n_months_scale  = rtriang(
            n = N_SIMULATIONS, 
            a = input$n_months_scale_dist[1], 
            b = input$n_months_scale_dist[2], 
            c = mean(c(input$n_months_scale_dist[1],
                       input$n_months_scale_dist[2]))
        ) %>% round()
    )
    
    print(rv2$simulation_grid_tbl)
    
    
    t0 <- Sys.time()
    rv2$simulation_results_tbl <- rv2$simulation_grid_tbl %>%
        mutate(adspend_results = pmap(
            .l = list(average_roas, n_months_learn, n_months_scale), 
            .f = function(average_roas, n_months_learn, n_months_scale) {
                
                adspend_profile_tbl <- create_adspend_profile(
                    start_date       = rv$input_start_date,
                    average_roas     = average_roas,
                    n_months_total   = rv$input_n_months_total,
                    n_months_learn   = n_months_learn,
                    n_months_scale   = n_months_scale,
                    adspend_learn    = rv$input_adspend_learn,
                    adspend_scale    = rv$input_adspend_scale
                )
                
                ret <- adspend_profile_tbl %>%
                    summarize_adspend_project()
                
                return(ret)
            
        }))
    t1 <- Sys.time()
    print(t1-t0)
    
    rv2$simulation_results_unnested_tbl <- rv2$simulation_results_tbl %>% 
    unnest(adspend_results)
    
    print(rv2$simulation_results_unnested_tbl)
    
    
    
    
})
```


<hr>




## Column

<br>

### Simulation Results (NPV of Profit)

```{r}
renderUI({
    req(rv2$simulation_results_unnested_tbl)
    
    probs <- c(0.05, 0.5, 0.95)
    quantiles_tbl <- rv2$simulation_results_unnested_tbl %>%
        summarise(
            q = probs,
            x = quantile(npv, probs = probs)
        )
    
    req(rv2$simulation_results_unnested_tbl)
    
    g <- rv2$simulation_results_unnested_tbl %>%
        ggplot(aes(npv)) +
        geom_histogram(fill = "#18bc9c", color = "white", alpha = 0.9) +
        geom_vline(aes(xintercept = median(npv)), color = "red", size = 1, linetype = 2) +
        geom_vline(aes(xintercept = quantile(npv, 0.05)), color = "blue", size = 1, linetype = 2) +
        geom_vline(aes(xintercept = quantile(npv, 0.95)), color = "blue", size = 1, linetype = 2) +
        theme_tq() +
        theme(
            panel.background = element_rect(fill = "black"),
            plot.background = element_rect(fill = "black"),
            text = element_text(colour = "white"),
            legend.background = element_rect(fill="black")
        )
    
    tagList(
        
            p(str_glue("The median NPV is {scales::dollar(quantiles_tbl$x[[2]])} with a 90% probability between {scales::dollar(quantiles_tbl$x[[1]])} (min) and {scales::dollar(quantiles_tbl$x[[3]])} (max)."))
        ,
        
            ggplotly(g, height = 750)
        
    )
    
    
})
```




