---
title: "Google Analytics Forecaster"
output:
    flexdashboard::flex_dashboard:
        orientation: columns
        theme: 
          bootswatch: "lux"
          bg: "white"
          fg: "white"
          primary: "#18bc9c"
          secondary: "#18bc9c"
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(
    echo    = FALSE,
    message = FALSE,
    warning = FALSE
)

library(shiny)
library(shinyjs)

library(modeltime)
library(modeltime.ensemble)
library(tidymodels)

library(tidyverse)
library(timetk)
library(lubridate)
library(janitor)
library(plotly)

```

``` {css}
.chart-title {
  background-color: black;
  color: white;
}

.chart-stage {
  background-color: black;
}

.section.sidebar {
  background-color: black;
}

.navbar.navbar-inverse {
  background-color: #18bc9c!important;
  box-shadow: 3px 3px 5px black;
}

.navbar-dark .navbar-brand, .navbar.navbar-inverse .navbar-brand {
  color:black;
}

.navbar.navbar-inverse ul.nav.navbar-nav>li.active>a {
  color:black;
}

.dashboard-column {
  background-color: black;
}

.section {
  background-color: black;
}

body {
  background-color:black;
}

.selectize-dropdown {
  background-color:black;
}
.selectize-input.full {
  background-color:black;
}
.selectize-input, .selectize-control.single .selectize-input.input-active {
  background-color:black;
}


.selectize-dropdown .active {
  background-color: #18bc9c;
  color: #f2f2f2;
}

```

```{r}
# DATA

google_analytics_tbl <- read_rds("data/google_analytics_by_page_daily.rds") %>%
  clean_names()

ga_summarized_tbl <- google_analytics_tbl %>%
  group_by(page_path) %>%
  summarise(
    count = n(),
    rank  = unique(rank),
    page_views = sum(page_views),
    viralness = sum(page_views) / count
  ) %>%
  mutate(desc = str_glue("Page: {page_path}
                          ----
                          Rank: {rank}
                          Count: {count}
                          Page Views: {scales::comma(page_views)}
                          Viralness: {round(viralness)}
                         "))

nested_modeltime_refit_tbl <- read_rds("models/nested_modeltime_refit_tbl.rds")

```



#

## Column {.sidebar}

<br>


#### What does the app do?

> Forecasts Google Analytics webtraffic for 20 Web Pages 

<hr>

#### Controls

__Use controls__ to select webpages and make the forecast.

```{r}
useShinyjs(rmd = TRUE)

shiny::selectInput(
  inputId = "page_path",
  label = "Page Path",
  selected = "/",
  choices = ga_summarized_tbl$page_path,
  selectize = TRUE
  
  
)

# actionButton(inputId = "apply", label = "Apply", icon = icon("play"))

actionButton(inputId = "reset", label = "Reset", icon = icon("sync"))


observeEvent(eventExpr = input$reset, handlerExpr = {
  
  updateSelectInput(
    inputId = "page_path",
    selected = "/"
  )

  # shinyjs::delay(ms = 300, expr = {
  #     shinyjs::click(id = "apply")
  # })
 
  
})


```

<hr>


## Column 

<br>

### GA Metrics

```{r}

renderPlotly({
  
  req(ga_summarized_tbl)
  
  filtered_df <- ga_summarized_tbl %>%
    filter(page_path %in% input$page_path)
  
  g <- ga_summarized_tbl %>%
    ggplot(aes(page_views, viralness, color = page_views, size = page_views)) +
    geom_point(aes(text=desc), alpha = 0.5) +
    
    geom_point(size = 11, shape = 1, color = "red", data = filtered_df) +
    
    scale_x_log10() +
    scale_y_log10() +
    geom_smooth(method = "lm", se = F) +
    labs(x = "Page Views (Log10 scale)", y = "Viralness (Log10 Scale)") +
    # scale_color_distiller(type = "seq") +
    scale_color_gradientn(colors = c("white", "#18bc9c")) +
    theme_minimal() +
    scale_size(range = c(3,10))+
    theme(
      panel.background = element_rect(fill = "black"),
      plot.background = element_rect(fill = "black"),
      text = element_text(colour = "white")
    ) 
  
  
  ggplotly(g)  
  
  
})

```


## Column

<br>

### Page Views (Forecast)

```{r}
renderPlotly({
  
  req(nested_modeltime_refit_tbl)
  
  df_filtered <- nested_modeltime_refit_tbl %>%
    extract_nested_future_forecast() %>%
    
    filter(page_path %in% input$page_path)
  
  if (nrow(df_filtered) == 0) {
    # If data wasn't forecasted (because of problem)
    
    df <- google_analytics_tbl %>%
      filter(page_path %in% input$page_path)
    
    wflw <- workflow() %>%
      add_model(window_reg(window_size = 1)) %>%
      add_recipe(recipe(page_views ~ date, df)) %>%
      fit(df)
    
    fcast_tbl <- modeltime_table(wflw) %>%
      modeltime_forecast(h = 28, actual_data = df)
    
    g <- fcast_tbl %>%
      plot_modeltime_forecast(.interactive = F, .legend_show = F)
    
    
  } else {
    g <- df_filtered %>%
      plot_modeltime_forecast(.interactive = F, .legend_show = F) 
  }
  
  g <- g +
      scale_color_manual(values = c("#18bc9c", "white")) +
      theme(
        panel.background = element_rect(fill = "black"),
        plot.background = element_rect(fill = "black"),
        text = element_text(colour = "white"),
        legend.background = element_rect(fill="black")
      ) +
      labs(title = str_glue("Page Path: {input$page_path}"))
  
  ggplotly(g)  
})

```

